################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o 

C_DEPS += \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Libraries/CMSIS/DSP/Source/StatisticsFunctions/%.o Libraries/CMSIS/DSP/Source/StatisticsFunctions/%.su Libraries/CMSIS/DSP/Source/StatisticsFunctions/%.cyclo: ../Libraries/CMSIS/DSP/Source/StatisticsFunctions/%.c Libraries/CMSIS/DSP/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F767xx -c -I../Core/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I"D:/Projects/stm32fun/f767zi_dac1/Libraries/CMSIS/DSP" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Libraries-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

clean-Libraries-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su
	-$(RM) ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.su
	-$(RM) ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.cyclo
	-$(RM) ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.cyclo
	-$(RM) ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.su ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.cyclo ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o ./Libraries/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-Libraries-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

